"""telemetry

Revision ID: 5230a41897f3
Revises: 796d6ce5873b
Create Date: 2026-08-09 22:47:34.853401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5230a41897f3'
down_revision: Union[str, Sequence[str], None] = '796d6ce5873b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('schema_version', sa.String(length=10), nullable=False),
    sa.Column('speed_kph', sa.Float(), nullable=False),
    sa.Column('accel_ms2', sa.Float(), nullable=False),
    sa.Column('lateral_accel_ms2', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('raw_frame', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_telemetry_trip_id_trips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry'))
    )
    op.create_index('ix_telemetry_trip_id_recorded_at', 'telemetry', ['trip_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_trip_id_recorded_at', table_name='telemetry')
    op.drop_table('telemetry')
    # ### end Alembic commands ###
