"""driving_events

Revision ID: f9f283e16596
Revises: 5230a41897f3
Create Date: 2026-08-09 23:14:24.396863

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9f283e16596"
down_revision: str | Sequence[str] | None = "5230a41897f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "driving_events",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("telemetry_id", sa.BIGINT(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("measured_value", sa.Float(), nullable=False),
        sa.Column("threshold_value", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["telemetry_id"],
            ["telemetry.id"],
            name=op.f("fk_driving_events_telemetry_id_telemetry"),
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_driving_events_trip_id_trips")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_driving_events")),
    )
    op.create_index(
        "ix_driving_events_trip_id_occurred_at",
        "driving_events",
        ["trip_id", "occurred_at"],
        unique=False,
    )
    op.add_column(
        "trips", sa.Column("speed_limit_kph", sa.Numeric(precision=6, scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "speed_limit_kph")
    op.drop_index("ix_driving_events_trip_id_occurred_at", table_name="driving_events")
    op.drop_table("driving_events")
    # ### end Alembic commands ###
